# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SBIOS0 <- function(data_list, basis, theta_eta_path, dimensions, init_params, region_idx, L_idx, batch_idx, lambda, prior_p, n_mcmc, start_delta, subsample_size, step, burnin = 0L, thinning = 10L, a = 1, b = 1, interval_eta = 10L, start_eta = 10L, start_saving_eta = 10L, stop_tuning_stepsize = 1e5L, all_sgld = 0L, sgld_freq = 50L, a_step = 0.001, b_step = 10, gamma_step = -0.55, update_individual_effect = 1L, testing = 0L, display_progress = TRUE) {
    .Call(`_SBIOS_SBIOS0`, data_list, basis, theta_eta_path, dimensions, init_params, region_idx, L_idx, batch_idx, lambda, prior_p, n_mcmc, start_delta, subsample_size, step, burnin, thinning, a, b, interval_eta, start_eta, start_saving_eta, stop_tuning_stepsize, all_sgld, sgld_freq, a_step, b_step, gamma_step, update_individual_effect, testing, display_progress)
}

big_address2mat <- function(bigmat_address) {
    .Call(`_SBIOS_big_address2mat`, bigmat_address)
}

set_seed <- function(seed) {
    invisible(.Call(`_SBIOS_set_seed`, seed))
}

complement <- function(start, end, n) {
    .Call(`_SBIOS_complement`, start, end, n)
}

extract_mask <- function(mask_fbm) {
    .Call(`_SBIOS_extract_mask`, mask_fbm)
}

update_Y_imp <- function(Y_star, Y_imp, beta, X_b, sigma_Y, gamma, X_q, region_idx, L_idx, Phi_Q, imp_vec_b, imp_p_b) {
    invisible(.Call(`_SBIOS_update_Y_imp`, Y_star, Y_imp, beta, X_b, sigma_Y, gamma, X_q, region_idx, L_idx, Phi_Q, imp_vec_b, imp_p_b))
}

update_Y_mat <- function(Y_mat, Y_imp, X_b, region_idx, imp_vec_b, imp_p_b) {
    invisible(.Call(`_SBIOS_update_Y_mat`, Y_mat, Y_imp, X_b, region_idx, imp_vec_b, imp_p_b))
}

SBIOSimp <- function(data_list, basis, dimensions, imp_idx_list, total_imp, init_params, region_idx, L_idx, batch_idx, lambda, prior_p, n_mcmc, start_saving_imp, start_delta, subsample_size, step, begin_eta = 0L, seed = 2022L, thinning = 1L, burnin = 0L, a = 1, b = 1, interval_eta = 10L, all_sgld = FALSE, a_step = 0.001, b_step = 10, gamma_step = -0.55, testing = TRUE, display_progress = TRUE, update_individual_effect = FALSE) {
    .Call(`_SBIOS_SBIOSimp`, data_list, basis, dimensions, imp_idx_list, total_imp, init_params, region_idx, L_idx, batch_idx, lambda, prior_p, n_mcmc, start_saving_imp, start_delta, subsample_size, step, begin_eta, seed, thinning, burnin, a, b, interval_eta, all_sgld, a_step, b_step, gamma_step, testing, display_progress, update_individual_effect)
}

method2_SGLD_multiGP_w_eta <- function(data_list, basis, dimensions, init_params, region_idx, L_idx, batch_idx, lambda, prior_p, n_mcmc, start_delta, subsample_size, step, burnin = 0L, thinning = 10L, a = 1, b = 1, interval_eta = 10L, start_eta = 10L, start_saving_eta = 10L, all_sgld = 0L, a_step = 0.001, b_step = 10, gamma_step = -0.55, update_individual_effect = 1L, testing = 0L, display_progress = TRUE) {
    .Call(`_SBIOS_method2_SGLD_multiGP_w_eta`, data_list, basis, dimensions, init_params, region_idx, L_idx, batch_idx, lambda, prior_p, n_mcmc, start_delta, subsample_size, step, burnin, thinning, a, b, interval_eta, start_eta, start_saving_eta, all_sgld, a_step, b_step, gamma_step, update_individual_effect, testing, display_progress)
}

method2_gs_no_mem <- function(data_list, basis, dimensions, init_params, region_idx, L_idx, batch_idx, lambda, prior_p, n_mcmc, start_delta, subsample_size, step, burnin = 0L, thinning = 10L, a = 1, b = 1, interval_eta = 10L, start_eta = 10L, start_saving_eta = 10L, update_individual_effect = 1L, seed = 2022L, testing = 0L, display_progress = TRUE) {
    .Call(`_SBIOS_method2_gs_no_mem`, data_list, basis, dimensions, init_params, region_idx, L_idx, batch_idx, lambda, prior_p, n_mcmc, start_delta, subsample_size, step, burnin, thinning, a, b, interval_eta, start_eta, start_saving_eta, update_individual_effect, seed, testing, display_progress)
}

